### ISSUE TITLE
AttributeError: 'StageInfo' object has no attribute 'env_vars'

### ISSUE THREAD

**Issue by nzxwang** [Mouse-Imaging-Centre/MICe-lab#12]
This seems to be an error with the executor. Need "stage" input to have this attribute somehow
Traceback (most recent call last):
      File "/micehome/nwang/repos/pydpiper/pydpiper/execution/pipeline_executor.py", line 175, in runStage
        process = subprocess.Popen(args, stdout=of, stderr=of, shell=True, env=stage.env_vars)
    AttributeError: 'StageInfo' object has no attribute 'env_vars'

**Comment by bcdarwin** [comment]
https://github.com/Mouse-Imaging-Centre/pydpiper/blob/master/pydpiper/execution/pipeline_executor.py#L133

**Comment by bcdarwin** [comment]
sigh ... I can't remember exactly when/why memory usage is/was a problem here ... this is rather unfortunate; I guess the problem is that in most cases per-object methods are just a waste ...

**Comment by bcdarwin** [comment]
also _someone_ dishonestly left out the type of 'stage' in the signature of `runStage` ...

**Comment by nzxwang** [comment]
thanks. I wrote a #TODO comment for disclosing the type of 'stage' in the signature of runStage and fxed the error which led to another error...

**Comment by bcdarwin** [comment]
A small request: it probably doesn't make sense to commit/push broken code to Github and then file issues against it unless other people are also working on it since then everyone subscribed gets notifications about nonexistent bugs ...
