### ISSUE TITLE
obviously incorrect reconstructions with Numpy >= 1.15

### ISSUE THREAD

**Issue by bcdarwin** [Mouse-Imaging-Centre/MICe-lab#18]
Courtesy of Brian:

"The depreciation note that I have pasted below is almost certainly the problem.

Multidimensional indexing with anything but a tuple is deprecated. This means that the index list in ind = [slice(None), 0]; arr[ind] should be changed to a tuple, e.g., ind = [slice(None), 0]; arr[tuple(ind)] orarr[(slice(None), 0)]. That change is necessary to avoid ambiguity in expressions such as arr[[[0, 1], [0, 1]]], currently interpreted as arr[array([0, 1]), array([0, 1])], that will be interpreted as arr[array([[0, 1], [0, 1]])] in the future."

(see https://github.com/numpy/numpy/blob/master/doc/release/1.15.0-notes.rst)

**Comment by nzxwang** [comment]
do we have any test data for this?

**Comment by bcdarwin** [comment]
Bisecting suggests that indeed the 1.14 -> 1.15 update causes this breakage, but the deprecation highlighted by Brian may not be the cause as no warning is raised and even in 1.17 the changed semantics are not in effect and the FutureWarning is still printed.

**Comment by bcdarwin** [comment]
This was caused by https://github.com/Mouse-Imaging-Centre/pyminc/issues/37, fixed in Pyminc 0.54.
